"""Dependency-light tools for validating already-local spool XML."""

from .contracts import (
    DEFAULT_XML_LIMITS,
    ExpandedQName,
    FieldProfile,
    InspectionManifest,
    NormalizationReceipt,
    SourceReceipt,
    XmlLimits,
)
from .xml_stream import (
    CharacterDataLimitError,
    DistinctQNameLimitError,
    MalformedXmlError,
    MarkupTokenLimitError,
    MissingRequiredFieldsError,
    NestingDepthLimitError,
    NoRowsFoundError,
    OutputCommitError,
    OutputValidationError,
    RemoteSourceRejectedError,
    RowByteLimitError,
    RowFieldLimitError,
    RowValueLimitError,
    SourceChangedError,
    SourceReadError,
    SourceValidationError,
    SpoolXmlError,
    UnsafeXmlError,
    XmlLimitError,
    inspect_xml,
    normalize_jsonl,
    write_json_transactional,
)

__version__ = "0.1.0"

__all__ = [
    "CharacterDataLimitError",
    "DEFAULT_XML_LIMITS",
    "DistinctQNameLimitError",
    "ExpandedQName",
    "FieldProfile",
    "InspectionManifest",
    "MalformedXmlError",
    "MarkupTokenLimitError",
    "MissingRequiredFieldsError",
    "NestingDepthLimitError",
    "NoRowsFoundError",
    "NormalizationReceipt",
    "OutputCommitError",
    "OutputValidationError",
    "RemoteSourceRejectedError",
    "RowByteLimitError",
    "RowFieldLimitError",
    "RowValueLimitError",
    "SourceChangedError",
    "SourceReadError",
    "SourceReceipt",
    "SourceValidationError",
    "SpoolXmlError",
    "UnsafeXmlError",
    "XmlLimitError",
    "XmlLimits",
    "inspect_xml",
    "normalize_jsonl",
    "write_json_transactional",
]
